//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace userLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int Id { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string istfAd { get; set; }
        public string shifre { get; set; }
        public string eMail { get; set; }
        public string telNom { get; set; }
    }
}
